### ISSUE TITLE
Add Visual Studio 2019 compatibility

### ISSUE THREAD

**Issue by jeffdapaz** [jeffdapaz/VisualChatGPTStudio#12]
Extension projects for Visual Studio 2022 are not backwards compatible and vice versa.

Separate projects are required for each edition, including separate publications in the marketplace.

However, it is possible to use the "shared project" technique so that the two projects share most of the code.

Due to this effort and taking into account that most developers are or will be using Visual Studio 2022, a version of this extension for Visual Studio 2019 will not be available at the moment.

However, if anyone is willing to implement the shared project technique, they have my support.

So I leave this issue open and the articles that explain how to proceed:

[Update a Visual Studio extension for Visual Studio 2022](https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#use-shared-projects-for-multi-targeting)

[Target a previous version when creating an extension in Visual Studio 2022](https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/target-previous-versions?view=vs-2022)

**Comment by jeffdapaz** [comment]
I found that extension projects for Visual Studio 2022 are not backwards compatible and vice versa.

Separate projects are required for each edition, including separate publications in the marketplace.

However, it is possible to use the "shared project" technique so that the two projects share most of the code.

Due to this effort and taking into account that most developers are or will be using Visual Studio 2022, a version of this extension for Visual Studio 2019 will not be available at the moment.

However, if anyone is willing to implement the shared project technique, they have my support.

So I leave this issue open and the articles that explain how to proceed:

[Update a Visual Studio extension for Visual Studio 2022](https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#use-shared-projects-for-multi-targeting)

[Target a previous version when creating an extension in Visual Studio 2022](https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/target-previous-versions?view=vs-2022)

**Comment by przemsiedl** [comment]
There are commit to make extension compatibile with vs2019 if someone need.
https://github.com/przemsiedl/VisualChatGPTStudio-VS2019

**Comment by jeffdapaz** [comment]
Hi @przemsiedl, very thanks for your collaboration!

Now I'm on vacation in another country without access to a computer where I can program.

I am be able to release this version more on less on May 20.

**Comment by jeffdapaz** [comment]
I already have the solution provided by @przemsiedl on my side, but adapted to use the shared projects technique to share most of the code between projects.

I will publish it shortly in the next release.
