### ISSUE TITLE
Use a submenu to list the ChatGPT commands

### ISSUE THREAD

**Issue by djack42** [jeffdapaz/VisualChatGPTStudio#15]
The context menu can really be too cluttered for small screens with many extensions active, you should introduce a submenu "chatGPT >" to list the availlable commands and add default shortcuts.

**Comment by jeffdapaz** [comment]
You're right. 

Will be a good improvement.

**Comment by jeffdapaz** [comment]
Commands moved to a submenu and added shortcuts.

Will be on next release.
