### ISSUE TITLE
Make custom commands available

### ISSUE THREAD

**Issue by jeffdapaz** [jeffdapaz/VisualChatGPTStudio#20]
The idea is to make new custom commands available in the context menu, and customizable through options.

This way will be possible create new commands other than those previously defined.

Maybe two commands it´s good enough for now.

Example:

...
Ask Anything ALT+8
**Custom 1 ALT+9
Custom 2 ALT+0**

**Comment by ryanbuening** [comment]
Would love custom commands! I have just been modifying the existing commands.

**Comment by jeffdapaz** [comment]
Yes, the idea is add on context menu (mouse right click -> Visual chatGPT Studio menu items).

**Comment by jeffdapaz** [comment]
Will be on next release.

Added 3 customizable commands:

One that inserts the answer before the selection;
One that inserts the answer after the selection;
And finally one that replaces the selection with the answer.
