### ISSUE TITLE
extension problem when calling the service

### ISSUE THREAD

**Issue by alvpaz** [jeffdapaz/VisualChatGPTStudio#26]
I just installed the extension, and when I entered the api key I got the message below what is missing?

![image](https://user-images.githubusercontent.com/7883678/233844357-0abe9ae8-8de1-400b-84a9-44c9beec4618.png)

![image](https://user-images.githubusercontent.com/7883678/233844395-85da1cba-9ded-40c9-9e4f-674c4e1c4cef.png)

**Comment by bembigonnadie** [comment]
up
