### ISSUE TITLE
Update supported/configurable models

### ISSUE THREAD

**Issue by ekomsctr** [jeffdapaz/VisualChatGPTStudio#28]
Hello,

first of all i would like to say i love this extension! Is nice to see the old good Visual Studio getting some love!
I just recently (today) started using this extension, and noticed some of the configurable models are out-of-date... See the screenshot down below:
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/13435555/1da785bb-48c5-4b0f-91f5-7066efe8d78a)
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/13435555/627d7205-aa19-48e7-9c14-14e8650ddae8)

I understand that models are volatile and i don't know if it's possible to retrieve them from some API, but i stumbled upon this [link](https://platform.openai.com/account/rate-limits), which i believe contains all the models available as of today.

It would be nice if the extension could reflect that list :)

**Comment by jeffdapaz** [comment]
Hi @ekomsctr , 

thanks for your feedback!

I will review the model list and publish the updated list on the next release.

**Comment by jeffdapaz** [comment]
Hi @ekomsctr,

I have already removed the discontinued templates and will soon publish a new release with this change.

Thanks again for alerting me.
