### ISSUE TITLE
Add comments, how can openai respond to Chinese?

### ISSUE THREAD

**Issue by snailg** [jeffdapaz/VisualChatGPTStudio#32]
Add comments, how can openai respond to Chinese?
thanks!

**Comment by jeffdapaz** [comment]
Translate the commands to chinese:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/8e64d2c1-d62b-41e1-bd3d-11a8202e46c6)

This is the way in this extension to OpenAI can respond in another languages.

**Comment by snailg** [comment]
thanks!
