### ISSUE TITLE
Error when trying to execute any command from context menu

### ISSUE THREAD

**Issue by ranasrule** [jeffdapaz/VisualChatGPTStudio#33]
Im getting the following Error when trying to execute any command from context menu:

![Screenshot 2023-06-01 172419](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/5023419/ff1ca220-926f-41da-99d2-f278501d161f)

**Comment by jeffdapaz** [comment]
Please, check on usage page if you have any credits. For example:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/47ec893e-401f-4edb-92a0-127a47a952fe)

[https://platform.openai.com/account/usage](https://platform.openai.com/account/usage)

**Comment by jeffdapaz** [comment]
Hi @ranasrule ,

I will close this issue, but if you still have this issue and need any help, please say something.
