### ISSUE TITLE
The Azure connection does not work in the menu and in the Visual chatGPT Studio view.

### ISSUE THREAD

**Issue by JManGr** [jeffdapaz/VisualChatGPTStudio#34]
Hello,

in the "Visual chatGPT Studio Turbo" view the Azure connection works fine, everything works. But when I try to make a request via the menu or via the "Visual chatGPT Studio" view, it does not work. I get the following error:

![grafik](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26242237/b388ae29-4629-4c65-8995-56b0f5567011)

Do I need to make any other settings or am I doing something wrong?

**Comment by jeffdapaz** [comment]
Hi @JManGr ,

Please, check this [issue](https://github.com/jeffdapaz/VisualChatGPTStudio/issues/31) for more information. You will find the answer there.

Basically you need create on azure two resources, one for the Turbo window and another for the menu commands and the other tool window.

**Comment by JManGr** [comment]
Hello @jeffdapaz.

OK, thanks, that worked.
