### ISSUE TITLE
Cannot Log with Azure account

### ISSUE THREAD

**Issue by pinsonth** [jeffdapaz/VisualChatGPTStudio#38]
Hello,

mis it possible to help me to connect with your Visual chatGPT Studio with Azure account?

I don’t know which information to put into the configuration screen.

thanks for help.

**Comment by jeffdapaz** [comment]
No problem.

Below are the necessary parameters that you need setup. The another ones that are not visible in this image you can leave with the default values.

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/4fa59392-494f-4280-a3d9-22f24e014028)

- **Deployment ID**: here you need set the deployment id that are using a completation model (I indicate Text-Davinci-3)
- **OpenAI Resource Name**: the resource name that the deployments is setupped
- **Turbo Chat API Version**: the currently Azure OpenAI API version 
- **Turbo Chat Deployment ID**: here you need set the deployment id that are using a Chat model (GPT-3.5-Turbo or GPT-4)
- **API Key**: here you need set the Azure OpenAI key
- **OpenAI Service**: select the Azure option

**Comment by jeffdapaz** [comment]
@pinsonth ,

I suppose you already could connect. So I'll close this issue, but if not, you can reopen again.
