### ISSUE TITLE
Add in the gpt-3.5-turbo-16k model? 

### ISSUE THREAD

**Issue by mtgeekman** [jeffdapaz/VisualChatGPTStudio#39]
Would it be possible to add in the **gpt-3.5-turbo-16k** model as an option to use?  This should allow for greater token length.

**Comment by jeffdapaz** [comment]
Will be on next release 😉

**Comment by mtgeekman** [comment]
Awesome, thank you!

**Comment by jeffdapaz** [comment]
New release published!
