### ISSUE TITLE
I hope the base API can be configured.

### ISSUE THREAD

**Issue by StimeKe** [jeffdapaz/VisualChatGPTStudio#40]
I hope to can change Base API because in some countries and regions, access to api.openai.com of OpenAI is not possible. Therefore i to use a reverse proxy to proxy the API, and I hope to be able to change the Base API.

Thank you very much.

**Comment by jeffdapaz** [comment]
Hi @StimeKe ,

thanks for the collaboration!

I already approved your pull request. I will publish this soon on next release.
