### ISSUE TITLE
Pause

### ISSUE THREAD

**Issue by Crack123451** [jeffdapaz/VisualChatGPTStudio#49]
How can I stop a request?
After starting request, for exampe, by Alt + 2 (unit-test), I watch a typing in my document by ChatGPT and I can't stop this process

**Comment by jeffdapaz** [comment]
At the moment is not possible.

Threre is already an [issue](https://github.com/jeffdapaz/VisualChatGPTStudio/issues/29)  opened about this. Check for more info. 

But I am thinking a way to implement this feature.
