### ISSUE TITLE
Using AzureAI still uses completion endpoint even though 2.0 states completion support removed.

### ISSUE THREAD

**Issue by DMCK96** [jeffdapaz/VisualChatGPTStudio#50]
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26749858/2f85cac1-9524-46d1-a99e-bb932da016ea)

I have not used this extension prior to 2.0 so there is no risk of leftover files. 

Why is it trying to access the completions endpoint that is no longer supported?

**Comment by jeffdapaz** [comment]
Hi @DMCK96, if you still have problems, you can reopen this issue.
