### ISSUE TITLE
GPT3 even with Model Language set to "GPT_4"

### ISSUE THREAD

**Issue by improwise** [jeffdapaz/VisualChatGPTStudio#52]
Not sure if this is the result of me doing something wrong either in the extension or in the OpenAI platform config but even though I have selected "GPT_4" as "Model language" in the settings for Visual ChatGGTP I still seem to get GPT3 according to the AI itself ("What version of OpenAI are you?").

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/2812422/f715b004-0c86-4051-9755-af5722448e68)

Thanks for a really nice extension BTW!

**Comment by jeffdapaz** [comment]
Hum, maybe you started a conversation, change the Model through the Options, and asked the question again in the same conversation. If you did this, it still use the "older" parametrization, but if you clear the chat, the new one will assume the new parameters.

Another way where you can check is [here](https://platform.openai.com/usage). You can see the requests divide by model:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/f89b32ab-0ce0-4476-95c9-1dec2ad5e2c8)

But on the next release probably I will add a feature to log the requests and responses. With that will be possible see all parameters that are be sending to OpenAI.

**Comment by improwise** [comment]
I have restarted VS2022 and even the computer but OpenAPI still claims to be GPT3. ChatGPT/OpenAPI has been a bit under the weather for the last 24 hours (I hope I didn't break it :) ) so will try again a bit later.

Improved logging sounds like a good idea, thanks for that.

**Comment by jeffdapaz** [comment]
Ok.

I already finish the logs implementation. Will be on next release 😉

When you have the opportunity, check the usage on OpenAI Portal, there you will be able to see if really are using only GPT-3.

**Comment by improwise** [comment]
It is actually a bit confusing as the usage on OpenAPI seem to indicate GPT4 but the AI itself is quite insistent on being GPT3 :) 

Prompt: 
Are you GPT4?

Response: 
No, I am not GPT-4. I am an AI model developed by OpenAI and currently, I am based on GPT-3.

Perhaps we have an AI identity crisis :)

**Comment by jeffdapaz** [comment]
Exactly, he don't know 😁

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/1eb58a2a-d66c-4803-b5c6-fa0ab95fce7d)

By the way, this it's the new feature that I will release soon, the requests and responses logs.
