### ISSUE TITLE
Remember what Visual ChatGPT Studio windows are open

### ISSUE THREAD

**Issue by Charl-Esterhuizen** [jeffdapaz/VisualChatGPTStudio#55]
I only use the Visual chatGPT Studio Window.
I never have the Visual chatGPT Studio Turbo or  Visual chatGPT Studio Solution Contexts windows open.
When I open my solution all 3 windows loads regardless of what was open when the solution was saved and I have to close the
"extra" to windows. 

Please make it so that it only open the window I select and not all 3 every time

**Comment by jeffdapaz** [comment]
Hi,

I need to check this. I don't know why this is happening, but it's not an act that I have deliberately programmed to act this way.

I will try to find a way to avoid this behavior.

**Comment by jeffdapaz** [comment]
@Charl-Esterhuizen , I already published a new version with the fix.

**Comment by Charl-Esterhuizen** [comment]
> @Charl-Esterhuizen , I already published a new version with the fix.

Thanks for the quick turnaround.
