### ISSUE TITLE
安装》使用报错：未能正确加载***包

### ISSUE THREAD

**Issue by kwonganding** [jeffdapaz/VisualChatGPTStudio#56]
Installed For VS 2022

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/16829626/3909058c-5a35-4afb-8e21-23647b03385f)

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/16829626/4786d7ea-fa80-4cec-bd82-15c7516ddc5b)

# 补充说明
* AppData\Local 下并没有上面错误提示的“**.db”文件，全盘搜索也没有。
* 另一个插件 “Codeium VSPackage”（也是一个AI插件）也报同样的错误了，这个插件安装、正常使用已经一周多了，今天安装完VisualChatGPTStudio 后报同样的错误了。
* VS2022版本：最新 17.8.1

##ActivityLog.xml 中的异常信息
SetSite failed for package [VisuallChatGPTStudioPackage]Source: 'VisualChatGPTStudio' Description: 未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 JeffPires.VisualChatGPTStudio.Utils.ChatRepository.GetChats() 位置 C:\TFS_GitHub\jeffdapaz\VisualChatGPTStudio\VisualChatGPTStudioShared\Utils\ChatRepository.cs:行号 93
   在 JeffPires.VisualChatGPTStudio.ToolWindows.Turbo.TerminalWindowTurboControl.StartControl(OptionPageGridGeneral options, Package package) 位置 C:\TFS_GitHub\jeffdapaz\VisualChatGPTStudio\VisualChatGPTStudioShared\ToolWindows\Turbo\TerminalWindowTurboControl.xaml.cs:行号 98
   在 JeffPires.VisualChatGPTStudio.Commands.TerminalWindowTurboCommand.<InitializeToolWindowAsync>d__12.MoveNext() 位置 C:\TFS_GitHub\jeffdapaz\VisualChatGPTStudio\VisualChatGPTStudioShared\Commands\TerminalWindowTurboCommand.cs:行号 108
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 JeffPires.VisualChatGPTStudio.Commands.TerminalWindowTurboCommand.<InitializeAsync>d__10.MoveNext() 位置 C:\TFS_GitHub\jeffdapaz\VisualChatGPTStudio\VisualChatGPTStudioShared\Commands\TerminalWindowTurboCommand.cs:行号 78
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 JeffPires.VisualChatGPTStudio.VisuallChatGPTStudioPackage.<InitializeAsync>d__8.MoveNext() 位置 C:\TFS_GitHub\jeffdapaz\VisualChatGPTStudio\VisualChatGPTStudioShared\VisuallChatGPTStudioPackage.cs:行号 64
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   在 Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

**Comment by wang20150419** [comment]
从 [visual studio 官方](https://marketplace.visualstudio.com/items?itemName=jefferson-pires.VisualChatGPTStudio)  安装，也出现是同样的报错。

**Comment by jeffdapaz** [comment]
@kwonganding , thanks for the feedback!

I will analyse this error and provider a fix as soon as I can.

**Comment by kwonganding** [comment]
@jeffdapaz It's been fixed.  👍👍👍

**Comment by wang20150419** [comment]
> @kwonganding and @wang20150419 ,
> 
> I already published a new version with fix.
> 
> Let me know if the issue was resolved.

This bug has been fixed and it is now working properly. Thank you!

**Comment by jeffdapaz** [comment]
Thanks for the feedback!
