### ISSUE TITLE
Add local LLM support 

### ISSUE THREAD

**Issue by 0Hate** [jeffdapaz/VisualChatGPTStudio#59]

**Comment by jeffdapaz** [comment]
Maybe can work out of the box.

Give a try. On extension options, you'll find there the Base Address parameter.

If you set with your local LLM address maybe works.

Tell me something later the result.

**Comment by jeffdapaz** [comment]
Hi @0Hate, I will close this issue, but if necessary you can reopen.

**Comment by redthista** [comment]
Looks like its calling /v1/v1 when requesting rather than just v1
[2024-02-03 13:15:37.244] [ERROR] Unexpected endpoint or method. (POST **/v1/v1**/chat/completions). Returning 200 anyway

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26851101/441a7cbd-576f-46ce-8291-c514ec7205df)

**Comment by mediaexplorer74** [comment]
> Looks like its calling /v1/v1 when requesting rather than just v1 [2024-02-03 13:15:37.244] [ERROR] Unexpected endpoint or method. (POST **/v1/v1**/chat/completions). Returning 200 anyway
> 
> ![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26851101/441a7cbd-576f-46ce-8291-c514ec7205df) ![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26851101/69e333de-61cc-49cd-8e80-e69445f4a686)

Hi, [redthista](https://github.com/redthista)! Can you fork this solution and fix this issue? In my country, OpenAI is not popular (it's paid and pay problem persist). I planned to use VisualChatGPTStudio with concunction of some "openllm" (llama, etc.). Also, the is openrouter.ai site/service with free Deepsik-r1 model...
