### ISSUE TITLE
The openai proxy interface is recommended

### ISSUE THREAD

**Issue by wangshuyu** [jeffdapaz/VisualChatGPTStudio#60]
Hello, your software is very useful and has solved many problems for me.
However, in China, we can't access openai, and most people don't understand azure, so I built an openai agent for the developers around me, which is fully compatible with openai, and the backend uses azure service nodes.
Can you promote it to Chinese users? In your software, the price of this agent interface is the same as that of openai, so I don't make money.
The interface address is: https://chat.wangshuyu.top/#/ApiDoc
--------------------------------------------------------------------------------------------------------------
你好，你的软件非常好用，解决了我很多问题。
但是在中国我们是访问不了openai的，大部分人对azure也不了解，所以我对给身边的开发人员自建了一个openai的代理，是完全兼容openai的，后端使用的是azure服务节点。
你是否可以推广给中国的用户呢，在你的软件里面， 这个代理接口价格和openai是一致的，我是不赚钱的。
接口地址是： https://chat.wangshuyu.top/#/ApiDoc

**Comment by jeffdapaz** [comment]
Hi @wangshuyu,

let's do a little different.

On Chinese [readme](https://github.com/jeffdapaz/VisualChatGPTStudio/blob/master/README-zh.md), there is the "认证" section: [(here)](https://github.com/jeffdapaz/VisualChatGPTStudio/blob/master/README-zh.md#%E8%AE%A4%E8%AF%81-).

Below the Azure sub section, add a new section that promotes your agent and some explanation how the people can use it.

After that create a pull request for me can review 🙂

**Comment by jeffdapaz** [comment]
Hi @wangshuyu, if you still like to edit the readme, be my guest.
