### ISSUE TITLE
can remove GetCommentChars(string filePath) default return 

### ISSUE THREAD

**Issue by GyJskz** [jeffdapaz/VisualChatGPTStudio#61]
hello jeffdapaz，
       can remove GetCommentChars(string filePath) default return "<!--"？because some language not list in code can use "The pre-defined commands setting" setting answer format replacement , so defalut return  just need return ""，thank you。

**Comment by jeffdapaz** [comment]
Hi @GyJskz,

I already published a new release with this fix. Thanks for the feedback.
