### ISSUE TITLE
Missing in toolbars

### ISSUE THREAD

**Issue by chefner67** [jeffdapaz/VisualChatGPTStudio#63]
After installing and reinstalling several times, I still do not see the Visual ChatGPT Studio in my toolbars menu. 

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/10273418/5c5a43c2-3d71-4dc9-a3c6-7a658e26c1fe)

**Comment by jeffdapaz** [comment]
@chefner67, you will find here:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/3560a35a-332a-4159-a538-4f8e13a1db30)

And the commands when you click on code editor with the right button:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/58affe90-ad19-426a-afa4-352d0d5ac541)

**Comment by jeffdapaz** [comment]
@chefner67 , I will close this issue. Be free to reopen if you still have problems.

**Comment by chefner67** [comment]
Yes, turned out a reinstall of Visual Studio was needed for this and other issues. It is resolved now. Thanks!
