### ISSUE TITLE
Local LLM Support - LM Studio

### ISSUE THREAD

**Issue by redthista** [jeffdapaz/VisualChatGPTStudio#65]
Issue with the call when changing baseapi:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26851101/3c72d7b3-7aa8-42cb-9f3f-eb40fc3caf7d)

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26851101/e817508a-2ce4-4342-a61f-0c7d9c8b9d68)

**Comment by redthista** [comment]
It looks like i needed to restart my vs after changing baseapi for it to start working: 
![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/26851101/8d38f82f-9c65-4c71-a6a6-9df979c5358a)

**Comment by jeffdapaz** [comment]
Hi @redthista.

Happy that you could solve the issue.
