### ISSUE TITLE
Invalid Request Error: str type expected

### ISSUE THREAD

**Issue by leejunweisg** [jeffdapaz/VisualChatGPTStudio#66]
Hi, I am trying to use the extension with my local OpenAPI-compatible LLM, but I am facing an "str type expected error".

This is the error response:
```
{
    "object": "error",
    "message": "[{'loc': ('body', 'messages'), 'msg': 'str type expected', 'type': 'type_error.str'}, {'loc': ('body', 'messages', 0, 'content'), 'msg': 'str type expected', 'type': 'type_error.str'}]",
    "type": "invalid_request_error",
    "param" null,
    "code": null
}
```

Upon inspecting the requests, I noticed that the plugin is sending the request in this structure:
```
{
    "messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "You are a programmer assistant called ..."
                }
            ]
        }
    ],
    ...
}
```

However, the [OpenAI API reference](https://platform.openai.com/docs/api-reference/chat/create) shows this structure instead:
```
{
    "messages": [
        {
            "role": "system",
            "content": "You are a programmer assistant called ..."
        }
    ],
    ...
}
```

May I know what could be the issue? Thanks! 🙏

**Comment by jeffdapaz** [comment]
Hi @leejunweisg,

I made tests and found the problem. The lasts plugin's versions came with this bug and another ones that I found now related if the "content" object.

I rollbacked the plugin version and now all are working fine. I will publish a new release soon.
