### ISSUE TITLE
Русский язык

### ISSUE THREAD

**Issue by slaymurs** [jeffdapaz/VisualChatGPTStudio#72]
Скажите пожалуйста, можно ли писать в чат GPT на русском, будет ли он меня понимать? Или у вас только все на английском?

**Comment by jeffdapaz** [comment]
Привет.

Скорее всего, ответ – да, вы сможете общаться полностью на русском языке. Например, я знаю людей, которые используют расширение на японском и китайском языках.

Кроме того, если вы хотите, чтобы все ответы возвращались на русском языке, просто переведите команды с английского на русский через параметры расширения.

Примечание: я использовал переводчик, чтобы писать на русском языке, так что не обращайте внимания, если оно будет плохо написано.
