### ISSUE TITLE
Add support for local LLM

### ISSUE THREAD

**Issue by Horschig** [jeffdapaz/VisualChatGPTStudio#73]
It's be awesome if you can add support for a local LLM, e.g. via LM Studio, Ollama or the like. Afair they support the OpenAI API, see e.g. https://ollama.com/blog/openai-compatibility.

**Comment by Horschig** [comment]
ah ye, saw the closed ones #59  and #65, so I'll give it a shot ;) I think a short manual would be handy though for people to try!

**Comment by jeffdapaz** [comment]
Hi @Horschig, thanks!

I will add some information on the plugin ReadMe about the local LLM usage.

**Comment by ViktorAgafonov** [comment]
Maybe this will help somehow. I don't know what to do with this:
https://github.com/awaescher/OllamaSharp

**Comment by Horschig** [comment]
it's been some time, and I am currently not programming anymore, but I am pretty sure that I got this to work with LMStudio. I had not tried with Ollama.
