### ISSUE TITLE
Empty system prompt for chat functionality is incompatible with local LLM (LM studio)

### ISSUE THREAD

**Issue by Horschig** [jeffdapaz/VisualChatGPTStudio#75]
When using the chat functionality, I get the following error:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/3985329/39e0e46f-eabc-42d1-bf22-6c0c0b48629f)

Inspecting the server logs revealed that he system prompt is empty, and LM studio does not like an empty content field. The Turbo chat works though.

**Comment by jeffdapaz** [comment]
Hi @Horschig, thanks to advise about this issue.

It's true, for the Tool Window the System Message is not being setted.

I will add a new optional parameter at the Extension Options to be possible set the System Message for the Tool Window. Will be on next release soon.

**Comment by jeffdapaz** [comment]
@Horschig,

I already published a new version that contains the new parameter "Tool Window System Message" in the Extension's Options". Now you can set a System Message to that window.

I think now you do not have this problem anymore with this custom LLM, but if not, you can come back here to tell.

**Comment by Horschig** [comment]
Thanks, this works now. However, I have the same issue when I want to use the "Ask Anything" function (Alt+8).

**Comment by jeffdapaz** [comment]
It's true, I forgot that the Ask Anything command also doesn't use System Message.

I will provide a correction and make it available in the next release.

Thanks for letting me know about.

**Comment by Horschig** [comment]
no worries, thanks for the effort!

**Comment by jeffdapaz** [comment]
Closing this issue because I published a new release with updated Ask Anything command that sends Tool Window System Message as System Message.
