### ISSUE TITLE
Error when I open the configuration dialog: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory

### ISSUE THREAD

**Issue by rcarubbi** [jeffdapaz/VisualChatGPTStudio#79]
I can't open the options to set my API key.

I get this error (extracted from the ActivityLog)
<description>SetSite failed for package [VisuallChatGPTStudioPackage]Source: &apos;VisualChatGPTStudio&apos; Description: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()&apos;.&#x000D;&#x000A;System.MissingMethodException: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()&apos;.&#x000D;&#x000A;   at JeffPires.VisualChatGPTStudio.Commands.TerminalWindowCommand.&lt;InitializeAsync&gt;d__9.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at JeffPires.VisualChatGPTStudio.Commands.TerminalWindowCommand.InitializeAsync(AsyncPackage package)&#x000D;&#x000A;   at JeffPires.VisualChatGPTStudio.VisuallChatGPTStudioPackage.&lt;InitializeAsync&gt;d__8.MoveNext() in C:\Source\GIT\VisualChatGPTStudio\VisualChatGPTStudioShared\VisuallChatGPTStudioPackage.cs:line 63&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>

**Comment by jeffdapaz** [comment]
@rcarubbi ,

What version of Visual Studio do you are using?

**Comment by rcarubbi** [comment]
2022, but it was not the latest update. I updated to the latest and it worked. Thanks for replying

**Comment by jeffdapaz** [comment]
Great!
