### ISSUE TITLE
Extension broken after update.

### ISSUE THREAD

**Issue by 0Hate** [jeffdapaz/VisualChatGPTStudio#85]
When I try to open the extension I get some visual studio errors only once and now extension doesn't work anymore. even after reinstall.

Where can I download previous versions?

![image](https://github.com/user-attachments/assets/692957c2-ea68-44f4-957d-33e0c46d80ec)

error in the logs:

SetSite failed for package [VisuallChatGPTStudioPackage]Source: &apos;VisualChatGPTStudio&apos; Description: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()&apos;.&#x000D;&#x000A;System.MissingMethodException: Method not found: &apos;Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.ThreadHelper.get_JoinableTaskFactory()&apos;.&#x000D;&#x000A;   at JeffPires.VisualChatGPTStudio.Commands.TerminalWindowCommand.&lt;InitializeAsync&gt;d__9.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at JeffPires.VisualChatGPTStudio.Commands.TerminalWindowCommand.InitializeAsync(AsyncPackage package)&#x000D;&#x000A;   at JeffPires.VisualChatGPTStudio.VisuallChatGPTStudioPackage.&lt;InitializeAsync&gt;d__8.MoveNext() in C:\Source\GIT\VisualChatGPTStudio\VisualChatGPTStudioShared\VisuallChatGPTStudioPackage.cs:line 63&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass21_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)

**Comment by jeffdapaz** [comment]
Unfortunately, it is not possible to download previous versions, however, a similar problem has been reported in the past, and it was resolved by updating Visual Studio to the latest version.

Is your VS on the latest version (17.11.5)? If not, can you update and check if the error is fixed?

**Comment by 0Hate** [comment]
> Unfortunately, it is not possible to download previous versions, however, a similar problem has been reported in the past, and it was resolved by updating Visual Studio to the latest version.
> 
> Is your VS on the latest version (17.11.5)? If not, can you update and check if the error is fixed?

Updating visual studio fixed the issue. Thank you very much for the help and amazing extension!

I have also learned how to backup extensions.

C:\Users\yourUserName\AppData\Local\Microsoft\VisualStudio\17.0_ef7a36b8\Extensions\u2ch5r4p.yha

inside the Extensions folder you can copy the extension folder and restore it in the future.
