### ISSUE TITLE
 here is a small problem. Why doesn't the vs2019 version have the copilot function?

### ISSUE THREAD

**Issue by ylyy** [jeffdapaz/VisualChatGPTStudio#86]
As the title.

**Comment by jeffdapaz** [comment]
Hi @ylyy,

to show the suggestions on editor to the user can confirm or not, is necessary use some microsoft packages, but I could not put this packages to work on VS 2019. I tried I lot of things , workarounds and packages versions, I also research for solutions on the web, but at the final I can't figure out how to put this to work on VS 2019.

So unfortunately I have to give up after some hours of triyng .

**Comment by ylyy** [comment]
OK. Thank you for your careful reply.
