### ISSUE TITLE
Regarding the issue of obtaining objects in IntelliCode.

### ISSUE THREAD

**Issue by zhaoM0** [jeffdapaz/VisualChatGPTStudio#91]
Hello,

I have reviewed your code and was wondering if IntelliCode provides an API for use. I haven't found any suitable documentation on this topic and would like to ask for your guidance.

Thank you.

**Comment by jeffdapaz** [comment]
Hi @zhaoM0,

As far as I know, the IntelliCode APIs aren't public, so there's no documentation available.

To add the "Copilot" feature to the extension, I had to rely on Code Completions. There's documentation for that below:

https://github.com/Microsoft/vs-editor-api/wiki/Modern-completion-walkthrough

But I have to say it doesn't help much. I had to turn to another project I found on GitHub to base myself on and add that feature to the extension.

All the necessary code to add code completions can be found in the "Copilot" folder of the extension, which includes:

1 - CommandFilter: this is used to intercept when the TAB key is pressed, to confirm the insertion of the code suggestion in the editor, or to capture the Enter key to start reading the code and look for the suggestion.

2 - TextViewCreationListener: this is a class needed to enable the extension to "watch" the actions taken in the code editors.

3 - InlinePredictionManager: this is basically the class that starts the process of capturing the code to create the completion suggestion.

4 - Suggestions: this is the class that has the routines to present the suggestion in the code editor.

**Comment by zhaoM0** [comment]
Thank you very much for your reply, it's very profitable. In addition, the Proposal API can provide completion capabilities, but it looks like it is exported through MEF and controlled by the framework, in which the scalability is really poor.
