### ISSUE TITLE
Problem with Ollama API in Visual ChatGPT Studio

### ISSUE THREAD

**Issue by przemsiedl** [jeffdapaz/VisualChatGPTStudio#92]
I'm currently testing this addon with Visual Studio 2019 and local models like Ollama. The issue is that you're setting an empty value for the "stop" property. This is causing Ollama to stop providing any responses, and it doesn't work properly. If possible, could you avoid setting this empty stop parameter? That way, it should work with Ollama.

Request Content: {"model":"deepseek-coder:1.3b","messages":[{"role":"system","content":"You are a helpful programmer of c# language."},{"role":"user","content":"just ping to me please"}],"temperature":0.9,"n":1,"stream":false,"stop":"","max_tokens":8192,"frequency_penalty":0.0,"presence_penalty":1.0}

Response Content: {"id":"chatcmpl-584","object":"chat.completion","created":1731542541,"model":"deepseek-coder:1.3b","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":""},"finish_reason":"stop"}],"usage":{"prompt_tokens":28,"completion_tokens":1,"total_tokens":29}}

In the picture example without stop property.
![image](https://github.com/user-attachments/assets/6af1a29f-a0ac-4c0c-8000-8394f4e337ae)

**Comment by jeffdapaz** [comment]
@przemsiedl,

do you mean instead set an empty value, set null?

**Comment by ViktorAgafonov** [comment]
Today I was advised to check LM Studio - unusual behavior like ollama is repeated.
By the way, pay attention to the “Add resume” command - it works by default, without editing the stop line.

**Comment by przemsiedl** [comment]
Yeah, the null value worked correctly. I'm not sure why, but not all models exhibited this behavior—about 7 out of 10 did. Setting the value to null works well.

CC: @jeffdapaz

**Comment by jeffdapaz** [comment]
Thanks for the feedback @przemsiedl.

I published a new version that will always send null for the stop parameter if it was not filled through the options.
