### ISSUE TITLE
ToolWindow / Shift + klick

### ISSUE THREAD

**Issue by mpagler** [jeffdapaz/VisualChatGPTStudio#95]
i want to use the Tool Window (Visual chatGBP Studio) in combination with SHIFT for Commands, but i get the error 
"Please, open the tool window first".

But the "Visual chatGPT Studio" is open.

I even closed it and opened it again... no change.

Visual Studio 2022
Version 17.12.2

Extension Version 3.2.0

**Comment by jeffdapaz** [comment]
@mpagler, I will check this and I will say something later.

**Comment by jeffdapaz** [comment]
@mpagler, I already published a new version with the fix.

Thanks to alert me about this issue.
