### ISSUE TITLE
Line Error

### ISSUE THREAD

**Issue by JJHACKER** [jeffdapaz/VisualChatGPTStudio#97]
Cant use , its show me only this error.
![image](https://github.com/user-attachments/assets/42f12a1b-4b90-4517-be7a-6532dc1617bf)

**Comment by jeffdapaz** [comment]
Can you replicate the error again, but with the parameters log requests and log responses enabled through the extension options?

After the error, get the logs though the output window and copy and paste here so I can analyze.

Don't forget to exclude from the logs your API key before post here.

**Comment by JJHACKER** [comment]
Problem solved, it was wrong url usage,
I used like this : https://api.avalapis.ir/v1/
Must be like this: https://api.avalapis.ir
